"""add ticket comments

Revision ID: 1eb0cc243ef5
Revises: 9531ee58f111
Create Date: 2026-02-20 08:06:57.888085

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '1eb0cc243ef5'
down_revision: str | None = '9531ee58f111'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
