"""add heartbeat model

Revision ID: 7bb77af09979
Revises: f6a7b8c9d0e1
Create Date: 2026-03-05 14:33:37.075553

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7bb77af09979'
down_revision: str | None = 'f6a7b8c9d0e1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heartbeats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('grace', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_ping_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name')
    )
    op.create_index(op.f('ix_heartbeats_project_id'), 'heartbeats', ['project_id'], unique=False)
    op.create_index(op.f('ix_heartbeats_token'), 'heartbeats', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heartbeats_token'), table_name='heartbeats')
    op.drop_index(op.f('ix_heartbeats_project_id'), table_name='heartbeats')
    op.drop_table('heartbeats')
    # ### end Alembic commands ###
