"""add user_api_tokens and created_via_ai

Revision ID: de9a49f6e3ae
Revises: 1bdf28994010
Create Date: 2026-02-22 11:12:29.474328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de9a49f6e3ae'
down_revision: Union[str, None] = '1bdf28994010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_api_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('token_prefix', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_api_tokens_user_id'), 'user_api_tokens', ['user_id'], unique=False)
    op.add_column('ticket_comments', sa.Column('created_via_ai', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('tickets', sa.Column('created_via_ai', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'created_via_ai')
    op.drop_column('ticket_comments', 'created_via_ai')
    op.drop_index(op.f('ix_user_api_tokens_user_id'), table_name='user_api_tokens')
    op.drop_table('user_api_tokens')
    # ### end Alembic commands ###
